name = "CellposeWrapper"
uuid = "5e162cc7-81ee-4364-8b50-7fd1be3e50be"
version = "0.1.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[weakdeps]
ImageIO = "82e4d734-157c-48bb-816b-45c225c6df19"
Images = "916415d5-f1e6-5110-898d-aaa5f9f070e0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[extensions]
CellposeWrapperVizExt = ["Plots", "Colors", "FileIO", "Images"]

[compat]
Colors = "0.12"
FileIO = "1"
ImageIO = "0.6"
Images = "0.26"
Plots = "1"
PyCall = "1"
julia = "1.10"
